### ISSUE TITLE
是如何做到判断cpu空闲状态的？

### ISSUE THREAD

**Issue by vortesnail** [WarrenJones/nemetric#4]
你好作者，我看了下源码，也看了你发的博客文章，但是关于cpu空闲这块还是很有疑问：
1、在 `document.visibilityState === 'hidden' ` 时，cpu就一定空闲吗？
2、我打开一个页面，不切换到其他页面，就是说 visibilitychange 的回调不会触发，我看了代码说是有一个 deadline 时间内执行，那在 deadline 时间内又是怎么确定 cpu 是空闲的呢？

希望作者能给予回答，若作者没时间的话可否给一个博客中所说的：

> 这是谷歌大神Phlip Walton 给出的一个解决方案

这个方案，我自己阅读～
谢谢啦～

**Comment by WarrenJones** [comment]
requestIdleCallback 就是在浏览器的空闲时段内调用的函数排队。deadline是为了保证cpu没有空闲的时间执行。document.visibilityState === 'hidden'是为了不在页面运作的时候执行

**Comment by vortesnail** [comment]
@WarrenJones 但是我在你的代码中看到，虽然声明了全局的 `requestIdleCallback`，但是实际上并没有用到这个API，而是自己写的：
```javascript
const requestIdleCallbackShim = (callback: any) => {
  const deadline = new IdleDealine(now());
  return setTimeout(() => callback(deadline), 0);
};
```

这样写难道是能模拟原生 `requestIdleCallback` 的效果吗？换个方式问就是，你自定义的这个垫片到底是怎么检测到 cpu 空闲的呢？

谢谢作者的耐心回答，我真的非常疑惑，就这部分代码读不懂～

**Comment by WarrenJones** [comment]
是的，模拟requestIdleCallback。然后不断轮询处理任务
